### ISSUE TITLE
After Nextcloud update to 18.0 no webinterface

### ISSUE THREAD

**Issue by Pixxelcrasher** [nextcloud/files_automatedtagging#139]
Hello,
after I update my nextcloud to version 18.0 i cant access my webinterface. It shows me al the time this error:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

My problem is that I have no logs cause they were deleted.
What can i do ?

PHP: PHP 7.3.13-1

**Comment by nickvergessen** [comment]
Did you update the app, or force enable the old version?

**Comment by adriaaah** [comment]
I don't want to hijack the issue but since I experienced it too, I thought it would be better to add the logs here instead of creating a new one. Please let me know if that's not the correct way.

I tried upgrading from a 17.0.3 and from 17.0.4 to 18 and got the same message regardless the source version: 
```
[timestamp] [php7:error] [pid 25832] [client x.x.x.x:42789] PHP Fatal error:  Declaration of OCA\\FilesAutomatedTagging\\Operation::validateOperation($name, array $checks, $operation) must be compatible with OCP\\WorkflowEngine\\IOperation::validateOperation(string $name, array $checks, string $operation): void in /var/www/mynextcloud/apps/files_automatedtagging/lib/Operation.php on line 35
```
I've found a similar issue on https://help.nextcloud.com/t/working-17-upgrade-in-web-to-18-500-http-error/69624/5 that was reported on GitHub but closed due to it couldn't be reproduced (https://github.com/nextcloud/server/issues/19003#event-3113604113)
