### ISSUE TITLE
Enhancement: Link to Documentation

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/files_automatedtagging#15]
HI, 
I am just exploring the features of the files_automatedtagging (menu item Workflow in Admin panel).
As perhaps many other users, I am new to this feature and would like to know(read) more about it. 
However there is **no Link** to the on line documentation available to learn more about this feature.
How to build rules, sample of rules. etc.

Links to online documentation are available for many other features.

regards, hitam4450

**Comment by runout-at** [comment]
Hi!
Are the rules the same as for Files Access Control?
As documented here: https://docs.nextcloud.com/server/10/admin_manual/configuration_files/files_access_control.html

if yes, then i miss a rule that triggers on uploading to a defined folder or shared (public) link. I would like to open an issue for that if there is no such possibility at the moment.

markus

**Comment by nickvergessen** [comment]
Yes, rules/checks are the same

**Comment by runout-at** [comment]
OK, thx.
Now I'm not sure if this request should go here for the plugin or if this is an issue fo the server because the rules are used from there. 
And there are more issues i don't know where to report: because (now) people can set/delete tags on shared things and if the `File retention` is used, which is based on tags, somebody could set a tag for file removal in X days on a file which was shared to him by somebody else who don't want the removal.
Yes, a bit off topic but i found no documentation to all that.

**Comment by nickvergessen** [comment]
> if yes, then i miss a rule that triggers on uploading to a defined folder or shared (public) link.

Just add a system/collaborative tag on the folder.

The problem about tag removal should be reported in the retention app:
https://github.com/nextcloud/files_retention

**Comment by AlexanderPlaza** [comment]
Hey, was just wondering now that we are on Nextcloud11 is there any documentation regarding this plugin?

**Comment by nickvergessen** [comment]
@AlexanderPlaza as mentioned above, the rules and checks are the same as on https://docs.nextcloud.com/server/10/admin_manual/configuration_files/files_access_control.html

So the only thing that needs additional documentation is that it applies the tags that you enter in the field. But I guess that should be somewhat clear?

**Comment by nickvergessen** [comment]
Better docs are now in https://docs.nextcloud.com/server/12/admin_manual/file_workflows/automated_tagging.html
